### ISSUE TITLE
Sender input field does not allow space character

### ISSUE THREAD

**Issue by jackwedi** [evanTheTerribleWarrior/Twilio-Outbound-Messaging#2]
![image](https://user-images.githubusercontent.com/36620818/167859111-8d731dbf-51a4-4005-9146-6ca671374126.png)

Would it be possible to allow spacing into the sender input ?

**Comment by evanTheTerribleWarrior** [comment]
Definitely. I added trimming thinking it could help avoid sender mistakes but spaces are allowed in alphanumeric so makes sense to have it.

 I can push the update tonight if that s ok

**Comment by evanTheTerribleWarrior** [comment]
I have updated it, can you recheck that everything is fine and then I close it?

**Comment by jackwedi** [comment]
Thx it's perfect!

**Comment by evanTheTerribleWarrior** [comment]
Definitely. I added trimming thinking it could help avoid sender mistakes
but spaces are allowed in alphanumeric so makes sense to have it.

 I can push the update tonight if that s ok
