### ISSUE TITLE
ERROR Invalid Serverless Project Structure

### ISSUE THREAD

**Issue by ProjectsLogistics** [evanTheTerribleWarrior/Twilio-Outbound-Messaging#3]
Let me say first that I am a novice with some knowledge. I am trying to help a friend. I am very  good at the hardware side, and excellent at networks. My first programing experience was in 1970 (10th grade) with Focal and Fortran on a DEC PDP8S (look it up). This is now driving me crazy, so any help would be idolized.

A few weeks ago, I (successfully) installed and tested the Twilio Programmable SMS "CSV to SMS Campaigns" located at https://www.twilio.com/blog/serverless-sms-marketing-campaigns-csv (https://www.twilio.com/blog/serverless-sms-marketing-campaigns-csv)

I had a URL of https://msg-9099.twil.io/,  https://casels-sms-8139.twil.io/,  https://msg-8254.twil.io/index.html all worked at one time or another. None work

I removed two "services" (SID beginning with ZS. I have a Messaging Service (ID beginning with MG).

I tried removing and reinstalling https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging but can no longer deploy. see screenshot below
![Twilio - Screenshot 2023-12-13 190542](https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging/assets/53759179/30b2df5a-6c96-4c59-9760-2ec9946a665e)

**Comment by evanTheTerribleWarrior** [comment]
Hello,

From what I understand you had initially installed the previous versions of the repository. If that is the case, and you now cloned the new version, then the structure is different that is why it throws an error.
In your Twilio-Outbound-Messaging directory, from the latest clone you did, you should have 2 folders, serverless and frontend. This is the structure of the new version, where I provide both the frontend and backend code. So you should run the serverless command in the "serverless" directory.

The new repo has installation instructions as well that makes the whole thing easier so free to check these out - there are also scripts that can be used to deploy everything at once.

But if you want to keep working with the older version of the repo, I have moved it to another branch.
to clone that older version you can do:
`git clone -b old_version https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging.git`

You can also see the old version here
https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging/tree/old_version

**Comment by ProjectsLogistics** [comment]
I appreciate your prompt and helpful response.
Many thanks for the work you do. In my professional life, I was  civil
trial attorney and worked extensively pro bono. It is a thankless but
satisfying effort.

By going on GitHub, I found your information but had some difficulty
understanding.  I am trying the use of zsh, and also working on rolling
back to the original  installation .

Thank you again.
Arthur

**Comment by evanTheTerribleWarrior** [comment]
No worries - your work is definitely harder :)

As for zsh: this is just an alternative of "bash" shell.

If you don't want to run the scripts as they are, you can open just .sh file itself and run the commands, the result should be the same.

```
# Remove any existing frontend build  and serverless deployed assets (if any)
rm -r ./frontend/build && find "./serverless/assets" -mindepth 1 -delete

# Create the new build
npm run --prefix frontend build

# Copy new build to serverless assets
cp -a ./frontend/build/. ./serverless/assets/

# Deploy app and functions
cd serverless && twilio serverless:deploy --override-existing-project
```

Do you have `npm` installed? this will be the main way to create the frontend application assets, that you can then copy over  to the serverless directory as shown in the commands

To explain better:
The older version had already the app resources created, but this has the negative that the developers don't have access to the app's source code in case they want to enhance/change it. 
In the new version there is both frontend and backend code, which you can tie together

**Comment by ProjectsLogistics** [comment]
Yes, I do have npm installed. I will try that just to learn.
Since I am using Windows, I found an article that looks like it can be
installed through Ubuntu.
Thank you. I’ll let you know how it goes.

**Comment by evanTheTerribleWarrior** [comment]
Yes you can use the WSL for that. let me know

**Comment by ProjectsLogistics** [comment]
So sorry to bother again.

I learned a little more about github, and was able to install (but not
fully test yet) the older version.

I used Google and installed WSL2, Ubuntu, and ZSH, (with some small
difficulty) and used it to install the current version to a different
directory (Twilio-Outbound-Casels) using Option 1. A lot of messages, but
seemed to otherwise go okay until the deploymnt part. I am attaching the
screenshots, hopefully in order, so you can see what's go.

Arthur

**Comment by evanTheTerribleWarrior** [comment]
Hey Arthur no worries! I am not sure I can see the screenshots though?

**Comment by ProjectsLogistics** [comment]
They are jpg files. How can I upload them to make it easier?
Should I send them inline? Gmail allows that but don’t know how they would
come through.

**Comment by evanTheTerribleWarrior** [comment]
On github you should be able to upload them directly in this issue:
https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging/issues/3

**Comment by esharksolutions** [comment]
![Screenshot 2023-12-15 120657](https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging/assets/14905198/09fa40e7-2089-467a-8fad-b51e775c7f37)
![Screenshot 2023-12-15 121335](https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging/assets/14905198/61a3d57f-52f9-4695-b2c0-da555d9f9e2b)
![Screenshot 2023-12-15 120813](https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging/assets/14905198/c2ff11e8-a685-4659-b798-441ea9fbf3a7)
![Screenshot 2023-12-15 122206](https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging/assets/14905198/1e06534b-439f-4fed-be1e-dfb2ada7d8ff)
![Screenshot 2023-12-15 114626](https://github.com/evanTheTerribleWarrior/Twilio-Outbound-Messaging/assets/14905198/51d5fcd9-a4b8-49b5-a000-e1beca96b3b1)

**Comment by evanTheTerribleWarrior** [comment]
hmmm can you do "npm install react-scripts" from within the `frontend` directory, wait for it to install it and try again and let me know if anything changes? i have it in the package.json so in theory the first npm install you did inside the frontend folder should have installed but give it a try

**Comment by evanTheTerribleWarrior** [comment]
ensure you have also properly installed react in WSL
https://learn.microsoft.com/en-us/windows/dev-environment/javascript/react-on-wsl

**Comment by esharksolutions** [comment]
Will try both and let you know.

**Comment by ProjectsLogistics** [comment]
The old version is working well.
Getting to the new one is frustrating me, but re-installing node, react,
and wsl2 moved me further and further along.

I am beginning to think that the problem is in the path/location of the
various sections. I will keep trying - I very rarely walk away once I start
something.

On another note, I would like to send you a token of my appreciation.

**Comment by ProjectsLogistics** [comment]
Sorry I hit send before I was done. Where can I send it to you?

**Comment by evanTheTerribleWarrior** [comment]
ok good to hear at least the old works, but yes will be good to get the newest working.
If you want, I can simply do like the old version - the reason it works more easily is that the old_version repository already has the build ready. I can create a build of the new version, provide it directly to you, and then you just need to place it in the right directory. of course that means you won't have the original source code (and is generally better to have the ability to clone the latest versions and build them locally), but if for now it does not matter we could do like that.

If that still doesnt work, happy to review this over a zoom/google meet call (will just need to communicate privately out of github)

Please dont worry about sending anything, a star on the Github repo is more than enough!

**Comment by esharksolutions** [comment]
I am pretty determined.  I’m going to keep working on the new one.
I will keep in touch. My gut tells me that I am messing up with the
directories.

**Comment by evanTheTerribleWarrior** [comment]
sure, let me know how it goes one way or another it's doable. Npm and all these package managements and dependencies can cause pains so you are not alone

**Comment by evanTheTerribleWarrior** [comment]
Havent heard back so I close this for now, feel free to open again if needed
